### ISSUE TITLE
Week 9 f2c Ready for Grading

### ISSUE THREAD

**Issue by lzingg1-matc** [madisoncollege-it-programs/python-scripting-lzingg1-matc#12]
no questions

**Comment by cethenmc** [comment]
I just noticed you did two separate issue tickets.  My last comment should have been in here in the Week 9 tempconversion ticket should have been in here.  Sorry about that.

**Comment by cethenmc** [comment]
![image](https://user-images.githubusercontent.com/112707666/207955565-934fb797-5a6b-4a8f-924a-678c72ea06e7.png)
