### ISSUE TITLE
week3 Assignment is ready for grading

### ISSUE THREAD

**Issue by lzingg1-matc** [madisoncollege-it-programs/python-scripting-lzingg1-matc#3]
no problems with this one

**Comment by cethenmc** [comment]
Hi, Luke.  #12 is incorrect.  Please count the entirety of the string, so you know the correct number for the length for the fill character to fill.  You did get #13 right, which is the same number of spaces as the dollar signs on the top.  Beginning in week 4, I will likely deduct for this, so please be careful.  Thanks.  ~Chris
