### ISSUE TITLE
Week 5 - Ready for grading

### ISSUE THREAD

**Issue by lzingg1-matc** [madisoncollege-it-programs/python-scripting-lzingg1-matc#5]
no problems!

**Comment by cethenmc** [comment]
so very close.  honestly one of the best attempts.  nice work!

#3's answers every question correctly but it is not following the request to "save the full file contents one line at a time to a variable."   I will record a 7 out of 8 on this one in the grade book for now, but please feel free to modify #3 to if you can get full credit.

Please reach out if you have questions.

Thanks.

Chris

**Comment by lzingg1-matc** [comment]
Okay, I think I fixed it. Using the loop I read through the files and appended them all to the same variable. I then calculated the length of that variable.

**Comment by cethenmc** [comment]
Looks good now.  Thanks, Luke
